export enum GameState {
    // the game is waiting for a second player to join
    INITIAL_STATE = 'INITIAL_STATE',
    // the game is waiting for a player to play their cards
    AWAIT_CARD_PLACEMENT = 'AWAIT_CARD_PLACEMENT',
    // the game is waiting for a decision about how cards resolve
    AWAIT_FLYING_FISH_MOVEMENT = 'AWAIT_FLYING_FISH_MOVEMENT',
    AWAIT_FOG_TARGET = 'AWAIT_FOG_TARGET',
    AWAIT_HARPOON_TARGET = 'AWAIT_HARPOON_TARGET',
    AWAIT_MOVEMENT_SET = 'AWAIT_MOVEMENT_SET',
    AWAIT_NET_TARGET = 'AWAIT_NET_TARGET',
    AWAIT_PILINGS_TARGET = 'AWAIT_PILINGS_TARGET',
    AWAIT_TIDAL_SURGE_TARGET = 'AWAIT_TIDAL_SURGE_TARGET',
    AWAIT_TIDAL_WAVE_TARGET = 'AWAIT_TIDAL_WAVE_TARGET',
    AWAIT_TORTOISE_TARGET = 'AWAIT_TORTOISE_TARGET',
    AWAIT_VOLCANIC_ERUPTION_TARGET = 'AWAIT_VOLCANIC_ERUPTION_TARGET',
    // the game is over
    FINISHED = 'FINISHED',
}
